#!/usr/bin/env python
import optparse

# add options to the option parser
parser = optparse.OptionParser()
parser.add_option('-d', '--dict',
                  default = None,
                  help    = 'The pronunciation dictionary file.')
parser.add_option('-c', '--counts',
                  default = None,
                  help    = 'The counts file.')

# parse options, arguments
options, args = parser.parse_args()
del parser

dict_words = set()
with open(options.dict, 'r') as f:
	for line in f:
		dict_words.add(line.split()[0].lower())

with open(options.counts, 'r') as f:
	for line in f:
		good  = True
		words = line.split()[:-1] # last token of each line is the count
		for word in words:
			if word.lower() not in dict_words:
				good = None
				break
		if good:
			print line.strip()
