
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.2'

_lr_method = 'LALR'

_lr_signature = '"\xc1\xab"\x13\x0b\xe2|:\xa0X\xe4<\xed\xc1\xab'
    
_lr_action_items = {'PIPE':([18,19,20,21,25,28,29,30,31,],[-8,-12,-7,27,-11,27,-9,-10,-6,]),'GREATER':([9,13,24,],[12,15,30,]),'SEMICOLON':([3,18,19,20,21,25,28,29,30,31,],[4,-8,-12,-7,26,-11,32,-9,-10,-6,]),'LESS':([4,6,7,8,11,14,16,18,19,20,22,23,25,26,27,29,30,31,32,],[5,-3,10,5,-2,17,17,-8,-12,17,17,17,-11,-4,17,-9,-10,17,-5,]),'EQUALS':([12,15,],[14,22,]),'LBRACKET':([14,16,18,19,20,22,23,25,27,29,30,31,],[16,16,-8,-12,16,16,16,-11,16,-9,-10,16,]),'STR':([0,2,4,5,6,8,10,11,14,16,17,18,19,20,22,23,25,26,27,29,30,31,32,],[2,3,7,9,-3,7,13,-2,18,18,24,-8,-12,18,18,18,-11,-4,18,-9,-10,18,-5,]),'RBRACKET':([18,19,23,25,29,30,],[-8,-12,29,-11,-9,-10,]),'$end':([1,6,8,11,26,32,],[0,-3,-1,-2,-4,-5,]),}

_lr_action = { }
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = { }
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'Grammar':([0,],[1,]),'Rule':([4,8,],[6,11,]),'Item':([14,16,20,22,23,27,31,],[19,19,25,19,25,19,25,]),'ItemList':([14,16,22,27,],[20,23,20,31,]),'RuleList':([14,22,],[21,28,]),'Model':([4,],[8,]),}

_lr_goto = { }
for _k, _v in _lr_goto_items.items():
   for _x,_y in zip(_v[0],_v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = { }
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> Grammar","S'",1,None,None,None),
  ('Grammar -> STR STR SEMICOLON Model','Grammar',4,'p_Grammar','jsgfparser.py',33),
  ('Model -> Model Rule','Model',2,'p_Model','jsgfparser.py',37),
  ('Model -> Rule','Model',1,'p_Rules','jsgfparser.py',42),
  ('Rule -> LESS STR GREATER EQUALS RuleList SEMICOLON','Rule',6,'p_Rule','jsgfparser.py',46),
  ('Rule -> STR LESS STR GREATER EQUALS RuleList SEMICOLON','Rule',7,'p_Rule_Public','jsgfparser.py',50),
  ('RuleList -> RuleList PIPE ItemList','RuleList',3,'p_Alternative','jsgfparser.py',54),
  ('RuleList -> ItemList','RuleList',1,'p_SingleRuleList','jsgfparser.py',59),
  ('Item -> STR','Item',1,'p_Word','jsgfparser.py',63),
  ('Item -> LBRACKET ItemList RBRACKET','Item',3,'p_Wlist','jsgfparser.py',67),
  ('Item -> LESS STR GREATER','Item',3,'p_Itemname','jsgfparser.py',71),
  ('ItemList -> ItemList Item','ItemList',2,'p_ItemList','jsgfparser.py',75),
  ('ItemList -> Item','ItemList',1,'p_SingleItemList','jsgfparser.py',80),
]
